spring.application.name=technicalinterview

spring.datasource.url=jdbc:postgresql://localhost:5432/user_db
spring.datasource.username=postgres
spring.datasource.password=pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

jwt.secret=thisisaverysecuresecretkeyforthisproject

# Springdoc OpenAPI/Swagger configuration
springdoc.openapi.urls[0]=/v3/api-docs
springdoc.openapi.ui.url=/swagger-ui.html
springdoc.openapi.ui.enabled=true
springdoc.openapi.model-and-view-support=true
springdoc.openapi.swagger-ui.oauth2RedirectUrl=http://localhost:8080/swagger-ui/oauth2-redirect.html
springdoc.openapi.swagger-ui.operationsSorter=method
